version: '3'

services:

  web_server:
    image: osds_web_server_image
    build:
      context: web_server
    container_name: osds_web_server_container
    volumes:
      - "../code:/var/www/osds:cached"
    ports:
      - "80:80"


  php:
    image: osds_php_image
    build:
        context: php
    container_name: osds_php_container
    volumes:
      - "../code:/var/www/osds:cached"


  database:
    image: mariadb
    container_name: mariadb_container
    restart: always
    command:
      "mysqld --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON"
    env_file: database/.env
    volumes:
      - "./database/container_data:/var/lib/mysql"
    ports:
      - "3306:3306"


  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"
