#web server

FROM nginx

#RUN apt-get update && \
#    apt-get install -y composer

#ADD nginx.conf /etc/nginx/

COPY hosts/ /etc/nginx/conf.d/

#COPY command.sh /tmp/command.sh
#RUN chmod +x /tmp/command.sh
#CMD /tmp/command.sh
